<a href="https://colab.research.google.com/github/anasarshad7677-netizen/Complete-ML-repo/blob/main/11_encoding_categorical_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Ordinal ecoding handling ordinal data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df  = pd.read_csv('/content/deepseek_csv_20261006_940c98.txt')
df.columns = ["age", "review", "qualification", "purchased", "gender"]
df.sample(5)

    age     review qualification purchased gender
10   40  excellent            pg        no      m
8    21        bad            ug        no      m
0    22       good            ug       yes      m
6    27       good            ug       yes      m
13   26  excellent            hs       yes      f

In [5]:
print(df.columns)

Index(['age', 'review', 'qualification', 'purchased', 'gender'], dtype='object')

In [6]:
df_new = df.iloc[:,1:4]

In [7]:
df_new.head()

      review qualification purchased
0       good            ug       yes
1  excellent            pg       yes
2        bad            hs        no
3       good            pg       yes
4  excellent            ug        no

In [8]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split (
df_new.iloc[:,0:2],df_new.iloc[:,-1],
 test_size = 0.2,
  random_state = 42
)

In [9]:
from sklearn.preprocessing import OrdinalEncoder

In [10]:
X_train.head()

       review qualification
9        good            hs
13  excellent            hs
1   excellent            pg
22  excellent            pg
5         bad            hs

In [11]:
oe = OrdinalEncoder(categories =[['excellent','good','bad'],['pg','ug','hs']] )

In [12]:
oe.fit(X_train)

OrdinalEncoder(categories=[['excellent', 'good', 'bad'], ['pg', 'ug', 'hs']])

In [13]:
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [14]:
X_train

array([[1., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [2., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 2.],
       [1., 1.]])

In [15]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(Y_train)
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [16]:
Y_train

array([1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1])

handling nominal data

In [17]:
df = pd.read_csv('/content/cars.csv')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [27]:
df['brand']

0        Maruti
1         Skoda
2         Honda
3       Hyundai
4        Maruti
         ...
8123    Hyundai
8124    Hyundai
8125     Maruti
8126       Tata
8127       Tata
Name: brand, Length: 8128, dtype: object

one hot ecoding using pandas

In [31]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

now using sckit learn

In [32]:
from sklearn.model_selection import train_test_split
X_train , X_test , Y_train , Y_test = train_test_split (
df.iloc[:,0:4],df.iloc[:,-1],
 test_size = 0.2,
  random_state = 42
)

In [33]:
from sklearn.preprocessing import OneHotEncoder

In [34]:
ohe = OneHotEncoder(sparse=False,drop = 'first')

In [45]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()

In [46]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']]).toarray()

In [47]:
X_train[['brand','km_driven']].values

array([['Tata', 2560],
       ['Honda', 80000],
       ['Hyundai', 150000],
       ...,
       ['Hyundai', 35000],
       ['Maruti', 27000],
       ['Maruti', 70000]], dtype=object)

In [48]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 11)